# Generated by Django 4.0.4 on 2023-09-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0004_csvdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedWaterFlowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('total_real_losses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_flow_analysis_central', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_flow_analysis_receive', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
