# Generated by Django 4.0.4 on 2023-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_csvdata_year_alter_csvdata_flow_analysis_central_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedwaterflowdata',
            name='build_consumer',
            field=models.DecimalField(decimal_places=2, default=7500, max_digits=10),
        ),
        migrations.AddField(
            model_name='classifiedwaterflowdata',
            name='non_revenue_water',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='classifiedwaterflowdata',
            name='system_input_volume',
            field=models.DecimalField(decimal_places=2, default=9000, max_digits=10),
        ),
    ]
