# Generated by Django 4.0.4 on 2023-09-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0007_classifiedwaterflowdata_build_consumer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedwaterflowdata',
            name='arbitrary_loss',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=10),
        ),
        migrations.AddField(
            model_name='classifiedwaterflowdata',
            name='unauthorised_consumption',
            field=models.DecimalField(decimal_places=2, default=400, max_digits=10),
        ),
    ]
